projectlibrary/admin/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint, request, make_response
from flask_login import login_user, logout_user, current_user, login_required
from projectlibrary import app, db, bcrypt
from projectlibrary.models import *
from projectlibrary.forms import NewStudentForm
from sqlalchemy import or_
import os
import logging
import uuid

admin = Blueprint('admin', __name__)


@admin.route("/", methods=['POST', 'GET'], defaults={'page':1})
@admin.route("/dashboard", methods=['POST', 'GET'], defaults={'page':1})
@admin.route("/dashboard/<int:page>", methods=['POST', 'GET'])
def dashboard(page):
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        # change to pagination
        students = Students.query.paginate(page=page, per_page=5)
        
        next_url = url_for('admin.dashboard', page=students.next_num) \
            if students.has_next else None
        
        prev_url = url_for('admin.dashboard', page=students.prev_num) \
            if students.has_prev else None
        return render_template('admin-dashboard.html', title="Super Admin Dashboard", students=students, next_url=next_url, prev_url=prev_url)

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})



@admin.route("/lecturers", methods=['POST', 'GET'], defaults={'page':1})
@admin.route("/lecturers/<int:page>", methods=['POST', 'GET'])
def lecturers(page):
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        # change to pagination
        lecturers = Lecturers.query.paginate(page=page, per_page=5)
        
        next_url = url_for('admin.lecturers', page=lecturers.next_num) \
            if lecturers.has_next else None
        
        prev_url = url_for('admin.lecturers', page=lecturers.prev_num) \
            if lecturers.has_prev else None
        return render_template('show-lecturers.html', title="Super Admin Dashboard", lecturers=lecturers)

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})



@admin.route("/categories", methods=['POST', 'GET'], defaults={'page':1})
@admin.route("/categories/<int:page>", methods=['POST', 'GET'])
def category_list(page):
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        categories = Categories.query.paginate(page=page, per_page=5)
        
        next_url = url_for('admin.category_list', page=categories.next_num) \
            if categories.has_next else None
            
        prev_url = url_for('admin.category_list', page=categories.prev_num) \
            if categories.has_prev else None
            
        return render_template('admin-categories.html', title="Super Admin Dashboard", categories=categories, prev_url=prev_url, next_url=next_url)

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})


@admin.route("/add-new/category", methods=['POST', 'GET'])
def add_category():
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        if request.method == "POST":
            category_name = request.form['name'].lower()
            
            category = Categories.query.filter_by(name=category_name.capitalize()).first()
            
            if category:
                flash('That Category Name is taken!')
                return redirect(url_for('admin.add_category'))
            
            new_category = Categories(name=category_name.capitalize())
            db.session.add(new_category)
            db.session.commit()
            
            flash('New Category Added!')
            return redirect(url_for('admin.category_list'))
        return render_template('add-category.html', title="Super Admin Dashboard")

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})



@admin.route("/edit-category/<category_id>", methods=['POST', 'GET'])
def edit_category(category_id):
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        category = Categories.filter_by(id=category_id).first()
        
        if request.method == "POST":
            category_name = request.form['name'].lower()
            category_id = request.form['id']
            
            #search for the category name, if the id isn't the same as this, refuse itttt
            
            exisiting = Categories.query.filter_by(name=category_name.capitalize()).first()
            if exisiting.id != category_id:
                flash('This Category Name already exists!')
                return redirect(url_for('admin.edit_category', category_id=category_id))
            
            category.name = category_name.capitalize()
            db.session.commit()
            
            flash('Category Updated')
            return redirect(url_for('admin.category_list'))
        
        return render_template('edit-category.html', title="Super Admin Dashboard", category=category)

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})



@admin.route("/delete-category/<category_id>", methods=['POST', 'GET'])
def delete_category(category_id):
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        cateogry = Categories.query.filter_by(id=category_id).first()
        
        if category:
            db.session.delete(category)
            db.session.commit()
            flash('Category Deleted')
            
        else:
            flash('That Category does not exist!')
            
        return redirect(url_for('admin.category_list'))
        

    logging.warn(request.__dict__)
    return make_response('Could not verify', 401, {'WWW-Authenticate': 'Basic realm="Login required"'})




@admin.route("/add/new-student", methods=['POST', 'GET'])
def create_student():
    admin_username = 'admin'
    admin_password = 'admin'

    if request.authorization and (request.authorization.username == admin_username and request.authorization.password == admin_password):
        if request.method == 'POST':
            name = request.form['name']
            username = request.form['username'].lower()
            email = request.form['email']
            index_number = request.form['indexnumber']
            group_id = request.form['groupid']
            raw_password = request.form['password']
            college = request.form['college']
            program = request.form['programme']
            group_leader = request.form['groupleader']
            staff_id = request.form['staffid']
            
            #validation
            student_check = Students.query.filter_by(username=username.capitalize()).first()
            lecturer_check = Lecturers.query.filter_by(username=username.capitalize()).first()
            
            if student_check or lecturer_check:
                flash('This Username is not available!', 'warning')
                return redirect(url_for('admin.create_student'))
            
            student_email = Students.query.filter_by(email=email).first()
            lecturer_email = Lecturers.query.filter_by(email=email).first()
            
            if student_email or lecturer_email:
                flash('This Email is taken!', 'warning')
                return redirect(url_for('admin.create_student'))
            
            lecturer_confirm = Lecturers.query.filter_by(staff_id=staff_id).first()
            if not lecturer_confirm:
                flash('That Staff ID does not exist', 'warning')
                return redirect(url_for('admin.create_student'))
            
            
            #groups validation
            # search through students, if that group_id exists, check if that student's supervisor is the same
            validate_supervisor = Students.query.filter_by(group_id=group_id).first()
            
            if validate_supervisor and validate_supervisor.supervisor != staff_id:
                flash('That is not the assigned supervisor for this group!', 'warning')
                return redirect(url_for('admin.create_student'))
            
            validate_leader = Students.query.filter_by(group_id=group_id, group_leader=True).first()
            
            if group_leader == '1' and validate_leader:
                flash('That group already has a leader!', 'warning')
                return redirect(url_for('admin.create_student'))
            
            
            index_check = Students.query.filter_by(index_number=index_number).first()
            if index_check:
                flash('That Index Number is unavailable!')
                return redirect(url_for('admin.create_student'))
            
            #hash the password
            password = bcrypt.generate_password_hash(raw_password).decode('utf-8')

projectlibrary/main/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint, request
from flask_login import login_user, logout_user, current_user, login_required
from projectlibrary import app, db, bcrypt
from projectlibrary.models import *
from  sqlalchemy.sql.expression import func



main = Blueprint('main', __name__)


@main.context_processor
def inject_user():
    user = current_user
    student = None
    lecturer = None
    categories = Categories.query.limit(6).all()
    if user.is_authenticated:
        student = Students.query.filter_by(id=user.id).first()
        lecturer = Lecturers.query.filter_by(id=user.id).first()
        
        
    return dict(student=student, lecturer=lecturer, categories=categories)


@main.route("/", methods=['POST', 'GET'], defaults={'page':1})
@main.route("/home/<int:page>", methods=['GET', 'POST'])
def home(page):
    #taking care of the reports
    reports = Reports.query.filter_by(published=True).paginate(page=page, per_page=4)
    recents = Reports.query.filter_by(published=True).order_by(Reports.updated_at.desc()).limit(5).all()
    report_len = Reports
    
    carousels = Reports.query.filter_by(published=True).order_by(func.random()).limit(5).all()
    
    
    next_url = url_for('main.home', page=reports.next_num) \
        if reports.has_next else None
        
    prev_url = url_for('main.home', page=reports.prev_num) \
        if reports.has_prev else None
            
        
    if request.method == 'POST':
        username = request.form['uname'].lower()
        password = request.form['psw'].lower()
        
        student = Students.query.filter_by(username=username.capitalize()).first()
        lecturer = Lecturers.query.filter_by(username=username.capitalize()).first()
        #update to hashpassword and lecturer login
        if student:
            if bcrypt.check_password_hash(student.password, password):
                login_user(student)
                return redirect(url_for('students.dashboard'))
            else:
                flash('Wrong username/password combination', 'warning')
                
        if lecturer:
            if bcrypt.check_password_hash(lecturer.password, password):
                login_user(lecturer)
                return redirect(url_for('lecturers.dashboard'))
            else:
                flash('Wrong username/password combination', 'warning')
                
        else:
            flash('Wrong username/password combination', 'warning')
    return render_template("Index.html", reports=reports, next_url=next_url, prev_url=prev_url, report_len=report_len, recents=recents, carousels=carousels)


@main.route("/abstract/<report_id>", methods=['GET', 'POST'])
def abstract(report_id):   
    report = Reports.query.filter_by(id=report_id).first()
    recents = Reports.query.filter_by(published=True).order_by(Reports.updated_at.desc()).limit(5).all()
    return render_template('abstract.html', title='Report Abstract', report=report, recents=recents)


@main.route("/full-post/<report_id>", methods=['GET', 'POST'])
def fullpost(report_id):    
    report = Reports.query.filter_by(id=report_id).first()
    return render_template('fullpost.html', title='Report Full Post', report=report)



@main.route("/colleges", methods=['POST', 'GET'])
def colleges():   
    return render_template('colleges.html', title='Colleges')


@main.route("/explore/topic/<topic>", methods=['POST', 'GET'], defaults={'page':1})
@main.route("/explore/topic/<topic>/<int:page>", methods=['POST', 'GET'])
def topic_explore(topic, page):
     #taking care of the reports
    reports = Reports.query.filter_by(published=True, topic=topic).paginate(page=page, per_page=4)
    recents = Reports.query.filter_by(published=True).order_by(Reports.updated_at.desc()).limit(5).all()
    report_len = Reports
    
    next_url = url_for('main.topic_explore', page=reports.next_num) \
        if reports.has_next else None
        
    prev_url = url_for('main.topic_explore', page=reports.prev_num) \
        if reports.has_prev else None
        
    return render_template('topic-explore.html', title=topic, reports=reports, prev_url=prev_url, next_url=next_url, report_len=report_len, recents=recents)


@main.route("/explore/college/<college>", methods=['POST', 'GET'], defaults={'page':1})
@main.route("/explore/college/<college>/<int:page>", methods=['POST', 'GET'])
def college_explore(college, page):
     #taking care of the reports
    reports = Reports.query.filter_by(published=True, college=college).paginate(page=page, per_page=4)
    recents = Reports.query.filter_by(published=True).order_by(Reports.updated_at.desc()).limit(5).all()
    report_len = Reports
    
    next_url = url_for('main.college_explore', page=reports.next_num) \
        if reports.has_next else None
        
    prev_url = url_for('main.college_explore', page=reports.prev_num) \
        if reports.has_prev else None
        
    return render_template('college-explore.html', title=college, reports=reports, prev_url=prev_url, next_url=next_url, report_len=report_len, recents=recents)


@main.route('/search/<query>', methods=['POST', 'GET'], defaults={'page':1})
@main.route('/search/<query>/<int:page>', methods=['POST', 'GET'])
def search(query, page):
    search_params = "%{}%".format(query)
    
    reports = Reports.query.filter(Reports.title.ilike(search_params) | Reports.abstract.ilike(search_params) | Reports.introduction.ilike(search_params) | Reports.literature_review.ilike(search_params) | Reports.methodology.ilike(search_params) | Reports.testing_and_evaluation.ilike(search_params) | Reports.conclusion.ilike(search_params)).paginate(page=page, per_page=5)
    
    
    recents = Reports.query.filter_by(published=True).order_by(Reports.updated_at.desc()).limit(5).all()
    report_len = Reports
    
    next_url = url_for('main.home', page=reports.next_num) \
        if reports.has_next else None
        
    prev_url = url_for('main.home', page=reports.prev_num) \
        if reports.has_prev else None
        
    return render_template('search-results.html', title="Search Results", reports=reports, recents=recents, report_len=report_len, next_url=next_url, prev_url=prev_url, query=query)


@main.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

projectlibrary/templates/add-category.html
{% extends "admin-layout.html" %}
{% block content %}
<!----------------------------- Main Site Section ------------------------------>

<div class="form" style="margin-top: 2rem;">
    <form action="" method="POST">
        <label for="name">Category Name</label>
        <input type="text" minlength="3" id="name" name="name" placeholder="Category Name" required>
        
        
        <input type="submit" value="Submit">
    </form>
</div>
<!----------------------------- // Main Site Section ------------------------------>

{% endblock content %}

projectlibrary/templates/admin-categories.html
{% extends "admin-layout.html" %}
{% block custom_styles %}
<style>
    .button {
        border: none;
    padding: 8px 29px;
    text-decoration: none;
    display: inline-block;
    cursor: pointer;
    text-align: center;
    margin: 4px 2px;
    border-radius: 26px;
    }
    .customers-container{
       max-width: 70rem !important;
    }
    .menu-button{
        margin-top: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 2rem;
    }
</style>
{% endblock custom_styles %}
{% block content %}
<!----------------------------- Main Site Section ------------------------------>

<button><a href="{{url_for('admin.add_category')}}">Add New Category</a></button>

<div class="customers-container">
    {% if categories.items | length != 0 %}
    <table id="customers">
        <thead>
            <th>ID</th>
            <th>Category Name</th>
            <th colspan="2">Action</th>
        </thead>
        {% for category in categories.items %}
        <tr>
            <td>{{category.id}}</td>
            <td>{{category.name}}</td>
            <td><a href="{{url_for('admin.edit_category', category_id=category.id)}}" class="edit button w3-button w3-black">Edit</a></td>
            <td><button onclick="document.getElementById('delete-{{category.id}}').style.display='block'" class="w3-button w3-red">Delete</button></td>
        </tr>
        
        <div id="delete-{{category.id}}" class="w3-modal" style="display: none;">
            <div class="w3-modal-content w3-animate-top w3-card-4">
                <header class="w3-container w3-teal">
                    <span onclick="document.getElementById('delete-{{category.id}}').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                    <h2>Confirm Delete</h2>
                </header>
                <div>
                    <a class="button" href="{{url_for('admin.delete_category', category_id=category.id)}}" style="background-color: #f44336;">Yes</a>
                    <button onclick="document.getElementById('delete-{{category.id}}').style.display='none'" class="button" style="background-color: #4CAF50;">No</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </table>
    {% else %}
        <center><p>No Categories Available!</p></center>
    {% endif %}
    
    <br><br>
    <div class="pagination flex-row">
    {# if there is a previous page, give it the prev link else leave it  #}
    {% if prev_url %}
    <a href="{{prev_url}}"><i class="fas fa-chevron-left"></i></a>
    {% else %}
    <a href="#"><i class="fas fa-chevron-left"></i></a>
    {% endif %}

    {% for page_num in categories.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
    {% if page_num %}
    {% if categories.page == page_num %}
    <a href="{{url_for('admin.category_list', page=page_num)}}" class="pages active-page">{{page_num}}</a>
    {% else %}
    <a href="{{url_for('admin.category_list', page=page_num)}}" class="pages">{{page_num}}</a>
    {% endif %}
    {% else %}
    <a href="#" class="pages">...</a>
    {% endif %}
    {% endfor %}

    {% if next_url %}
    <a href="{{next_url}}"><i class="fas fa-chevron-right"></i></a>
    {% else %}
    <a href="#"><i class="fas fa-chevron-right"></i></a>
    {% endif %}
</div>



{% endblock content %}

projectlibrary/templates/admin-search-results.html
{% extends "admin-layout.html" %}
{% block custom_styles %}
<style>
    .button {
        border: none;
    padding: 8px 29px;
    text-decoration: none;
    display: inline-block;
    cursor: pointer;
    text-align: center;
    margin: 4px 2px;
    border-radius: 26px;
    }
    .customers-container{
       max-width: 70rem !important;
    }
    .menu-button{
        margin-top: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 2rem;
    }
</style>
{% endblock custom_styles %}
{% block content %}

<!----------------------------- Main Site Section ------------------------------>
<div class="menu-button">
    <button><a href="{{url_for('admin.create_student')}}">Add New Student</a></button>
    <button><a href="{{url_for('admin.create_lecturer')}}">Add New Lecturer</a></button>
    <button id="showStudents"><a href="{{url_for('admin.dashboard')}}">Show Students</a></button>
    <button id="showLecturers"><a href="{{url_for('admin.lecturers')}}">Show Lecturers</a></button>
</div>


<div id="resultsTable" class="customers-container">
    {% if users.items | length != 0 %}
    <table id="customers">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Username</th>
            <th>Programme</th>
            <th>Email</th>
            <th colspan="2">Action</th>
        </thead>
        {% for user in users.items %}
        <tr>
            <td>{{user.id}}</td>
            <td>{{user.name}}</td>
            <td>{{user.username}}</td>
            <td>{{user.program}}</td>
            <td>{{user.email}}</td>
            {#<td><a href="{{url_for('admin.edit_student', student_id=user.id)}}" class="edit button w3-button w3-black">Edit</a></td>
            <td><button onclick="document.getElementById('delete-{{student.id}}').style.display='block'" class="w3-button w3-red">Delete</button></td>#}
        </tr>
        
        {#<div id="delete-{{student.id}}" class="w3-modal" style="display: none;">
            <div class="w3-modal-content w3-animate-top w3-card-4">
                <header class="w3-container w3-teal">
                    <span onclick="document.getElementById('delete-{{student.id}}').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                    <h2>Confirm Delete</h2>
                </header>
                <div>
                    <a class="button" href="{{url_for('admin.delete_user', user_id=student.id)}}" style="background-color: #f44336;">Yes</a>
                    <button onclick="document.getElementById('delete-{{student.id}}').style.display='none'" class="button" style="background-color: #4CAF50;">No</button>
                </div>
            </div>
        </div>#}
        {% endfor %}
    </table>
    {% else %}
    <p>No User Exists in the Database</p>
    {% endif %}
    
    <br><br>
{#

#}
</div>


{% endblock content %}

projectlibrary/templates/fullpost.html
{% extends "main-layout.html" %}
{% block custom_styles %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static', filename='css/Style.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/pdfViewer.css')}}">
{% endblock custom_styles %}

{% block content %}
    <!-- ------------x---------------  Navigation --------------------------x------------------- -->

    <!----------------------------- Main Site Section ------------------------------>

    <main>
        <!-- <div class="chapters">
            <ul>
                <li><a href="">Chapter 1</a></li>
                <li><a href="">Chapter 2</a></li>
                <li><a href="">Chapter 3</a></li>
                <li><a href="">Chapter 4</a></li>
                <li><a href="">Chapter 5</a></li>
            </ul>
        </div> -->
        <div class="pdf-container">
            <iframe src="{{url_for('static', filename='pdfs/'+report.full_report)}}" width="100%" height="100%">
            </iframe>
          </div>
    </main>

    <!---------------x------------- Main Site Section ---------------x-------------->


{% endblock content %}

projectlibrary/templates/student-layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
    <title>Project Library: {{title}} </title>
    {% else %}
    <title>Project Library : Home Page</title>
    {% endif %}

    <!-- Font Awesome Icons -->
    
    <link rel="stylesheet" href="{{url_for('static', filename='css/all.css')}}">
    {% block css_files1 %}{% endblock css_files1 %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <!-- --------- Owl-Carousel ------------------->
    <link rel="stylesheet" href="{{url_for('static', filename='css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/owl.theme.default.min.css')}}">

    <!-- ------------ AOS Library ------------------------- -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/aos.css')}}">

    <!-- Custom Style   --> 
    <link rel="stylesheet" href="{{url_for('static', filename='css/Style.css')}}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <link rel="stylesheet" href="{{url_for('static', filename='css/lecturerdashboard.css')}}">
    <link rel="shortcut icon" type="image/jpg" href="https://apps.knust.edu.gh/img/logo.png">
    {% block custom_styles %}
    <style>
    .w3-modal-content {
            width: 400px;
        }

        .w3-container p {
            padding: 1rem;
        }
    
    </style>
    {% endblock custom_styles %}
</head>

<body>

    <!-- ----------------------------  Navigation ---------------------------------------------- -->
    <nav class="nav">
        <div class="nav-menu flex-row">
            <div class="nav-brand">
                <a href="{{url_for('main.home')}}" class="text-gray"><img src="https://apps.knust.edu.gh/img/logo.png" alt="Knust logo"></a>
            </div>
            <div class="toggle-collapse">
                <div class="toggle-icons">
                    <i class="fas fa-bars"></i>
                </div>
            </div>
            <div>
                <ul class="nav-items">
                    <li class="nav-link">
                        <a href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-link">
                        <a href="{{url_for('main.colleges')}}">Colleges</a>
                    </li>
                    <li class="nav-link">
                        <a href="{{url_for('students.dashboard')}}">Project-Group</a>
                    </li>
                    {% if current_user.group_leader %}
                    <li class="nav-link">
                        <a href="{{url_for('students.upload_report')}}">Upload</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="social text-gray">
                <div class="avatar"><i class="fa fa-user"></i></div>
                <p>Welcome {{current_user.username}}</p>
                <a href="{{url_for('main.logout')}}" class="logout">
                    <span class="material-icons" >
                        logout
                    </span> 
                </a>
            </div>
        </div>
    </nav>

    <!-- ------------x---------------  Navigation --------------------------x------------------- -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!----------------------------- Main Site Section ------------------------------>
    {% block content %}{% endblock content %}

    <!---------------x------------- Main Site Section ---------------x-------------->

<div class="w3-container">
        <div id="flashModal" class="w3-modal">
            <div class="w3-modal-content w3-animate-top w3-card-4">
                <header class="w3-container w3-teal">
                    <span onclick="document.getElementById('flashModal').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                    <h2>Message</h2>
                </header>
                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    <ul class=flashes>
                        {% for category, message in messages %}
                        <li class="{{ category }}">
                            <center>
                                <p class="m-auto p-auto">{{ message }}</p>
                            </center>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
    
    <script>
       {% with messages = get_flashed_messages(with_categories=true) %}
       {% if messages %}
            $(window).on('load', function(){
                $('#flashModal').css('display', 'block');
            });
       {% endif %}
       {% endwith %}
    </script>

</body>

</html>